---
- name: Install make dependencies
  apt:
    name:
      - subversion
      - autoconf
      - build-essential
      - zlib1g-dev
      - libssl-dev
      - libgsm1-dev
      - pkg-config
      - speex

- name: Checkout yate subversion repository
  subversion:
    repo: http://voip.null.ro/svn/yate/trunk
    dest: "{{ yate_build_directory }}"

- name: Run Autogen script
  command: ./autogen.sh
  args:
    chdir: "{{ yate_build_directory }}"

- name: Run Configure script
  command: ./configure --enable-sse2 --with-libspeex --enable-g722-webrtc=no
  args:
    chdir: "{{ yate_build_directory }}"

- name: Build Yate
  command: make
  args:
    chdir: "{{ yate_build_directory }}"

- name: Install Yate
  command: make install-noapi
  args:
    chdir: "{{ yate_build_directory }}"

- name: Configure Libraries
  command: ldconfig

- name: Copy yate service file
  copy:
    src: "{{ yate_build_directory }}/packing/deb/yate.init"
    dest: /etc/init.d/yate
    mode: 755
    remote_src: yes
